language: python

python:
- '3.6'
- '3.7'
- '3.8'
- '3.9'
#- '3.10'

before_install:
- python --version
- pip install -U pip
- pip install -U pytest
- pip install codecov
- pip install coverage
- pip install pytest-cov
#- sudo apt-get -y install gfortran liblapack-dev

install:
- pip install -r requirements.txt
- pip install wheel


script:
- python setup.py bdist_wheel
- pytest -v --cov-config=.coveragerc --cov-report term --cov=hello_linlin hello_linlin/tests/

after_success:
- codecov
